### ISSUE TITLE
Service properties

### ISSUE THREAD

**Issue by michaelvogt** [OpenArCloud/oscp-spatial-service-discovery#14] opened 2021-04-01 18:46 UTC
I'd like to propose to extend the interface Service with a property called `properties`.

The meaning of this property would be specific for a service. For example a GeoPose service could define what sensordata it accepts / requires, when image sensor data is accepted, which format/size/color model would be ideal.

For a headless client for sparcl, it could be initial values of the automerge document.

**Comment by jamesjackson** [comment] 2021-04-13 04:28
Yes, SSD needs something like this. Note that the existing `capabilities` property was intended to perform a similar function through a list of K/V pairs. The property name and structure can be refined as needed.

**Comment by michaelvogt** [comment] 2021-04-18 12:06
Yes, would be great when capabilities could be renamed, to make its broader usage clear. 
Can actually stay as key/value pairs.

**Comment by jamesjackson** [comment] 2021-05-03 04:16
Fixed in master, ready for test. Thanks !

**Closed as completed** 2021-05-07 04:28 UTC
